server:
  port: 7002
eureka:
  instance:
    hostname: eureka-7002.com
  client:
    register-with-eureka: false #不注册到Eureka
    fetch-registry: false #不从注册中心获取服务
    serviceUrl:
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka # http://localhost:7002/eureka
      defaultZone:  http://eureka-7001.com:7001/eureka
