server:
  port: 9004
spring:
  application:
    name: USER-CONSUMER-FEIGN-HYSTRIX #不要使用下划线
eureka:
  client:
    service-url:
      # defaultZone: http://localhost:7001/eureka #告诉服务提供者要把服务注册到哪儿
      defaultZone: http://eureka-7001.com:7001/eureka,http://eureka-7002.com:7002/eureka
  instance:
    prefer-ip-address: true  #在注册中心显示Eureka客户端真实ip地址
    ip-address: 127.0.0.1 #指定自己的ip信息，不指定的话会自己寻找
feign:
  hystrix:
    enabled: true #开启熔断支持
  client:
    config:
      remote-service:  #服务名，填写default为所有服务
        connectTimeout: 3000
        readTimeout: 3000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
